
services:
  postgres:
    image: postgres:18
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: torchi
      POSTGRES_PASSWORD: torchi
      POSTGRES_DB: torchi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db/schema:/docker-entrypoint-initdb.d # init script
volumes:
  pgdata:
